trigger:
  branches:
    include:
      - main  # Trigger pipeline on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specifies Python 3.x

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Set up Python environment and install dependencies'

  - script: |
      python app.py
    displayName: 'Run Python script'
